// Generated by CoffeeScript 1.7.1
(function() {
  var Hex, Player;

  window.game = {
    players: [],
    dev_cards: [],
    hexes: [],
    active_player: null,
    add_player: function() {
      return new Player;
    },
    find_player: function(id) {
      return this.players[parseInt(id) - 1];
    },
    add_row: function(row) {
      var adjustment, hex, indent_cols, new_row, _i, _ref;
      indent_cols = _.max(_.pluck(HEX_ROWS, 'hexes')) - row['hexes'];
      adjustment = 0;
      if (indent_cols > 0) {
        adjustment = indent_cols * (0.9 * HEX_WIDTH_EM + HEX_SPACING);
      }
      new_row = $('<div>').addClass('hex-row').css('margin-left', "" + adjustment + "em").appendTo('#board');
      for (hex = _i = 1, _ref = row['hexes']; 1 <= _ref ? _i <= _ref : _i >= _ref; hex = 1 <= _ref ? ++_i : --_i) {
        new Hex(new_row);
      }
      if (!row['landlocked']) {
        return new_row.children(':first-child, :last-child').addClass('sea').find('.hex-image').addClass('sea');
      }
    },
    find_hex: function(id) {
      return this.hexes[parseInt(id) - 1];
    },
    populate_hexes: function() {
      var hex, resource, shuffled_hexes, _i, _len, _ref;
      shuffled_hexes = _.shuffle(HEX_DECK);
      $('.hex:not(.sea)').removeClass('brick ore wood wheat sheep desert').find('.hex-image').removeClass('brick ore wood wheat sheep desert');
      _ref = $('.hex:not(.sea)');
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        hex = _ref[_i];
        resource = shuffled_hexes.pop();
        $(hex).addClass(resource);
        $(hex).find('.hex-image').addClass(resource);
      }
      return log.msg('Populated hexes.');
    }
  };

  window.bank = {
    sheep: RESOURCE_MAX,
    wheat: RESOURCE_MAX,
    brick: RESOURCE_MAX,
    wood: RESOURCE_MAX,
    ore: RESOURCE_MAX
  };

  window.log = {
    msg: function(content) {
      var new_msg;
      return new_msg = $('<li>').addClass('log-msg').html(content).appendTo($('#log-msgs'));
    }
  };

  Player = (function() {
    function Player() {
      game.players.push(this);
      this.id = game.players.length;
      this.name = "Player " + this.id;
      this.red = this.random_color();
      this.green = this.random_color();
      this.blue = this.random_color();
      this.dom_box = this.build_box();
      this.victory_points = 0;
      log.msg("" + (this.colored_el('span', this.name)) + " has joined the game.");
    }

    Player.prototype.random_color = function() {
      return Math.floor(Math.random() * 256);
    };

    Player.prototype.rgb = function() {
      return "" + this.red + "," + this.green + "," + this.blue;
    };

    Player.prototype.anti_rgb = function() {
      return "" + (256 - this.red) + "," + (256 - this.green) + "," + (256 - this.blue);
    };

    Player.prototype.build_box = function() {
      var box;
      return box = $('<div>').addClass('player').data('player-id', this.id).css({
        'background-color': "rgb(" + (this.rgb()) + ")",
        'border-color': "rgb(" + (this.anti_rgb()) + ")"
      }).appendTo($('#players'));
    };

    Player.prototype.colored_el = function(el, content) {
      return "<" + el + " style='color: rgb(" + (this.rgb()) + ");'>" + content + "</" + el + ">";
    };

    return Player;

  })();

  Hex = (function() {
    function Hex(row) {
      this.dom_hex = this.build_hex(row);
    }

    Hex.prototype.build_hex = function(row) {
      var hex;
      return hex = $(HEXAGON_NODE).appendTo(row);
    };

    return Hex;

  })();

  $(document).ready(function() {
    var player, row, _i, _j, _len;
    for (player = _i = 1; 1 <= STARTING_PLAYERS ? _i <= STARTING_PLAYERS : _i >= STARTING_PLAYERS; player = 1 <= STARTING_PLAYERS ? ++_i : --_i) {
      game.add_player();
    }
    for (_j = 0, _len = HEX_ROWS.length; _j < _len; _j++) {
      row = HEX_ROWS[_j];
      game.add_row(row);
    }
    game.populate_hexes();
    return $('#players').on('click', '.player', function() {
      var id;
      $('.active').removeClass('active');
      $(this).addClass('active');
      id = $(this).data('player-id');
      return game.active_player = game.find_player(id);
    });
  });

}).call(this);
