// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    var player, row, _i, _j, _len;
    for (player = _i = 1; 1 <= STARTING_PLAYERS ? _i <= STARTING_PLAYERS : _i >= STARTING_PLAYERS; player = 1 <= STARTING_PLAYERS ? ++_i : --_i) {
      game.add_player();
    }
    for (_j = 0, _len = HEX_ROWS.length; _j < _len; _j++) {
      row = HEX_ROWS[_j];
      game.add_row(row);
    }
    game.populate_hexes();
    game.populate_roads();
    game.populate_buildings();
    $('#players').on('click', '.player', function() {
      var id;
      $('.active').removeClass('active');
      $(this).addClass('active');
      id = $(this).data('player-id');
      return game.active_player = game.find_player(id);
    });
    return $('input').on('change', function(e) {
      var value;
      value = $(this).val();
      $('#board-pane').css('transform', "rotate(" + value + "deg)");
      return $('.probability').css('transform', "rotate(" + (-value) + "deg)");
    });
  });

}).call(this);
