// Generated by CoffeeScript 1.7.1
(function() {
  window.graph_richness = function(n) {
    var ctx, current_richness_as_array, data, i, myBarChart, r, richness_keys, richness_values, _i;
    for (i = _i = 1; 1 <= n ? _i <= n : _i >= n; i = 1 <= n ? ++_i : --_i) {
      game.populate_hexes();
      r = stats.calculate_richness();
      if (richnesses[r]) {
        richnesses[r] += 1;
      } else {
        richnesses[r] = 1;
      }
    }
    richness_keys = _.keys(richnesses);
    richness_values = _.values(richnesses);
    current_richness_as_array = _.map(richnesses, function(v, k) {
      var kint;
      kint = parseInt(k);
      return (kint === stats.calculate_richness()) * (_.max(richnesses));
    });
    data = {
      labels: richness_keys,
      datasets: [
        {
          label: 'Richness Distribution',
          data: richness_values
        }, {
          label: 'Current Richness',
          fillColor: "rgba(151,187,205,1)",
          pointColor: '#666',
          data: current_richness_as_array
        }
      ]
    };
    ctx = document.getElementById("myChart").getContext("2d");
    return myBarChart = new Chart(ctx).Line(data, {
      'bezierCurve': false
    });
  };

}).call(this);
