// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    var player, row, _i, _j, _len;
    for (player = _i = 1; 1 <= STARTING_PLAYERS ? _i <= STARTING_PLAYERS : _i >= STARTING_PLAYERS; player = 1 <= STARTING_PLAYERS ? ++_i : --_i) {
      game.add_player();
    }
    for (_j = 0, _len = HEX_ROWS.length; _j < _len; _j++) {
      row = HEX_ROWS[_j];
      game.add_row(row);
    }
    game.populate_hexes();
    game.populate_roads();
    game.populate_buildings();
    $('#board-pane').on('click', '.building.unowned.clickable, .road.unowned.clickable', function() {
      var associated_object, id, is_road;
      id = $(this).data('id');
      is_road = $(this).hasClass('road');
      if (is_road) {
        associated_object = game.find_road(id);
      } else {
        associated_object = game.find_building(id);
      }
      return associated_object.owned_by(game.active_player);
    });
    $('#board-pane').on('click', '.plantable.road', function() {
      var id, road;
      id = $(this).data('id');
      player = game.active_player;
      road = game.find_road(id);
      player.unplaced_roads -= 1;
      road.owned_by(player);
      return game.next_planter();
    });
    $('#board-pane').on('click', '.plantable.building', function() {
      var building, id;
      id = $(this).data('id');
      building = game.find_building(id);
      player = game.active_player;
      player.unplaced_settlements -= 1;
      building.owned_by(player);
      $('.building').removeClass('plantable');
      return $('.road.unowned').addClass('plantable');
    });
    $('#log form').on('submit', function(e) {
      var field, message;
      e.preventDefault();
      field = $('form input');
      message = field.val();
      if (message !== '') {
        if (game.active_player) {
          log.msg("" + (game.active_player.name_span()) + ": " + message);
        }
        return field.val('');
      }
    });
    return $('#board-pane').on('click', '.building.owned.clickable', function() {
      var id;
      id = $(this).data('id');
      return game.find_building(id).upgrade();
    });
  });

}).call(this);
